CREATE TABLE IF NOT EXISTS users (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    name VARCHAR(100)
        NOT NULL,

    email VARCHAR(150)
        NOT NULL
        UNIQUE,

    address VARCHAR(250)
        NOT NULL

);
