{
 "title": "Microservice User - Observabilidad",
 "tags": [
  "microservicios",
  "fastapi",
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "Latencia HTTP P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Cache HIT total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "microservice_cache_hits_total", "legendFormat": "HIT" }
   ]
  },
  {
   "title": "Cache MISS total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "microservice_cache_misses_total",
     "legendFormat": "MISS"
    }
   ]
  },
  {
   "title": "Errores Redis total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(microservice_cache_errors_total)",
     "legendFormat": "Errores"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "microservice_cache_hits_total / clamp_min(microservice_cache_hits_total + microservice_cache_misses_total, 1)",
     "legendFormat": "Hit ratio"
    }
   ]
  },
  {
   "title": "Cache HIT vs MISS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(microservice_cache_hits_total[$__rate_interval])",
     "legendFormat": "HIT/s"
    },
    {
     "expr": "rate(microservice_cache_misses_total[$__rate_interval])",
     "legendFormat": "MISS/s"
    }
   ]
  }
 ]
}